version: '3.8'

networks:
  qonto:
    driver: bridge

services:
  qonto-service:
    image: adrianoccosta/qonto:latest
    container_name: qonto-service
    hostname: qonto-service
    restart: always
    ports:
      - "7777:8080"
    environment:
      DATABASE_FILE_PATH: ./qonto_accounts.sqlite
    networks:
      - qonto